base: main

title: Слияние dev->main

body: |
  ## Описание изменений

  Пожалуйста, опишите изменения, внесенные в эту ветку.

  ## Влияние на пользователей

  Пожалуйста, опишите, как эти изменения повлияют на пользователей.

  ## Тестирование

  Пожалуйста, опишите, какие тесты были проведены для этой ветки.
