package "React Application" {
    [Login Page]
    [Contacts Page]
    [About Company Page]
    [User Management Page]
    [Lot Management Page]
    [Group Management Page]
    [Lot Info Page]
    [Request Page]
}
package "Redux Store" {
    [Auth Slice]
    [Lots Slice]
    [SupplierProperties Slice]
    [SupplierSpecialistProperties Slice]
    [AdministratorProperties Slice]
}

actor User
actor "Поставщик" as Supplier
actor "Администратор" as Administrator
actor "Специалист по снабжению" as Specialist


User --> [Login Page]: views
User --> [Contacts Page]: views
User --> [About Company Page]: views
Specialist --> [About Company Page]: views
Supplier --> [About Company Page]: views
Specialist --> [Contacts Page]: views
Specialist --> [Lot Management Page]: views
Supplier --> [Contacts Page]: views
Specialist --> [Lot Info Page]: views
Supplier --> [Lot Info Page]: views
Supplier --> [Request Page]: views
Administrator --> [User Management Page]: views
Administrator --> [Group Management Page]: views

[Login Page] --> [React Components]: renders login form
[Contacts Page] --> [React Components]: renders contacts content
[User Management Page] --> [React Components]: renders user management features
[Lot Management Page] --> [React Components]: renders lot management features
[Group Management Page] --> [React Components]: renders group management features
[About Company Page] --> [React Components]: renders contact info
[Request Page] --> [React Components]: renders management request

[React Components] --> [Middleware]: dispatches actions
[Middleware] --> [Redux Store]: dispatches actions
[Middleware] --> [Backend API Client]: sends requests to backend
[Backend API Client] --> [Backend API]: communicates with backend server

@enduml
