name: Pull Request Template

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - synchronize
    paths:
      - '.github/PULL_REQUEST_TEMPLATE.md'

jobs:
  create-pull-request-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Pull Request Template
        run: |
          template_file='.github/PULL_REQUEST_TEMPLATE.md'
          if [ "${GITHUB_BASE_REF}" = "dev" ]; then
            echo "# Dev to Main" > $template_file
          elif [ "${GITHUB_BASE_REF}" = "main" ]; then
            echo "# Main to Dev" > $template_file
          fi